######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 19 04:20:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
ICON = quebec.icns
HEADERS += MainWindow.h
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cpp
